"""slack webhook on installations

Revision ID: 3f084542824e
Revises: e1d6e5a369a2
Create Date: 2026-07-30 14:56:11.954659

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3f084542824e"
down_revision: str | None = "e1d6e5a369a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "installations", sa.Column("slack_webhook_ciphertext", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("installations", "slack_webhook_ciphertext")
    # ### end Alembic commands ###
