"""api_keys installation nullable for global agent connection

Revision ID: 7051e79f9870
Revises: 3f084542824e
Create Date: 2026-07-30 17:43:11.989367

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7051e79f9870'
down_revision: str | None = '3f084542824e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'installation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'installation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
