"""app_config table for UI-entered credentials

Revision ID: c8930f517df0
Revises: 7051e79f9870
Create Date: 2026-07-30 19:05:01.277088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c8930f517df0"
down_revision: str | None = "7051e79f9870"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_config")
    # ### end Alembic commands ###
