"""PR creation node — branch, commit, push, open PR.

Uses the git CLI in the workdir (it already has auth via extraHeader on clone —
for push we re-supply the header per invocation, never persisting the token).
Branch names are deterministic so a re-push of the same finding updates the
existing branch instead of spamming new PRs.
"""

import asyncio
import base64
import re

from agents.state import GuardianState
from apps.api.github.auth import installation_token
from apps.api.github.client import GitHubClient
from core.config import get_settings
from core.logging import get_logger
from core.schemas import PullRequestRef

log = get_logger("pr_creator")


def branch_name(finding, commit_sha: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", finding.rule_id.lower()).strip("-")[:40]
    return f"gitguardian/fix-{slug}-{commit_sha[:7]}"


async def _git(args: list[str], cwd: str, auth_header: str | None = None) -> tuple[int, str, str]:
    full = ["git"]
    if auth_header:
        full += ["-c", f"http.extraHeader=Authorization: Basic {auth_header}"]
    full += args
    proc = await asyncio.create_subprocess_exec(
        *full,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    return proc.returncode, out.decode(), err.decode()


def pr_body(state: GuardianState) -> str:
    f = state["current_finding"]
    fix = state["fix"]
    test = state["test_result"]
    return f"""## 🛡️ GitGuardian AI — Automated Security Fix

| | |
|---|---|
| **Rule** | `{f.rule_id}` |
| **Severity** | {f.severity.upper()} |
| **File** | `{f.file_path}:{f.start_line}` |
| **Scanner** | {f.tool} |
| **Confidence** | {fix.confidence} |
| **LLM cost** | ${state.get("llm_cost_usd", 0):.4f} |

### What was wrong
{f.message}

### The fix
{fix.explanation}

### Verification
- ✅ Fix re-scanned — original rule no longer fires
- ✅ Generated pytest suite **passed** in an isolated container ({test.duration_seconds:.1f}s)

```
{test.output[-800:]}
```

---
> ⚠️ **Human review required.** This PR was generated by an AI agent. The tests pass,
> but passing tests are evidence, not proof — review the diff before merging.

Generated by GitGuardian AI · commit `{state["commit_sha"][:7]}`
"""


async def pr_creator_node(state: GuardianState) -> dict:
    settings = get_settings()
    finding = state["current_finding"]
    fix = state["fix"]
    repo = state["repo_full_name"]
    branch = branch_name(finding, state["commit_sha"])

    token = await installation_token(state["installation_id"])
    auth = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    workdir = state["workdir"]

    bot = settings.github_app_bot_name
    await _git(["config", "user.name", f"{bot}[bot]"], workdir)
    await _git(
        ["config", "user.email", f"{settings.github_app_id}+{bot}[bot]@users.noreply.github.com"],
        workdir,
    )

    rc, _, err = await _git(["checkout", "-b", branch], workdir)
    if rc != 0:
        rc, _, err = await _git(["checkout", branch], workdir)  # exists from a previous push
    if rc != 0:
        raise RuntimeError(f"cannot create branch: {err[:300]}")

    await _git(["add", finding.file_path, fix.test_file_path], workdir)
    msg = (
        f"fix(security): {finding.rule_id} in {finding.file_path}\n\n"
        "Generated by GitGuardian AI — review before merging."
    )
    rc, _, err = await _git(["commit", "-m", msg], workdir)
    if rc != 0 and "nothing to commit" not in err:
        raise RuntimeError(f"commit failed: {err[:300]}")

    rc, _, err = await _git(
        ["push", "--force-with-lease", "origin", branch], workdir, auth_header=auth
    )
    if rc != 0:
        raise RuntimeError(f"push failed: {err[:300]}")

    async with GitHubClient(state["installation_id"]) as client:
        existing = await client.find_open_pr(repo, branch)
        if existing:
            pr_ref = PullRequestRef(
                number=existing["number"], url=existing["html_url"], branch=branch
            )
            await client.comment_on_pr(repo, existing["number"], "🔄 Fix updated after new push.")
        else:
            default_branch = await client.get_default_branch(repo)
            title = f"🛡️ Fix {finding.severity}: {finding.rule_id} in {finding.file_path}"
            pr = await client.create_pr(repo, title, pr_body(state), branch, default_branch)
            pr_ref = PullRequestRef(number=pr["number"], url=pr["html_url"], branch=branch)

    await log.ainfo("PR opened", url=pr_ref.url, rule=finding.rule_id)
    return {"prs": [pr_ref], "events": [f"pr_creator: PR #{pr_ref.number} {pr_ref.url}"]}
