"""Local pipeline — same agent graph, but operating on your local repo.

Differences from the (removed) webhook pipeline:
  - router: no clone — the workdir IS your repo's working tree
  - pr: local git + `gh` CLI with YOUR auth (no GitHub App)
  - notify: terminal summary + Langfuse trace (no check-runs)
"""

import asyncio
import os
import re
import shutil

from langgraph.graph import END, StateGraph

from agents.classifier.node import classifier_node
from agents.fix_generator.apply import FixValidationError, apply_fix, validate_with_rescan
from agents.fix_generator.node import fix_generator_node
from agents.scanner.node import scanner_node
from agents.state import GuardianState
from agents.test_generator.runner_node import test_generator_node
from core.logging import get_logger
from core.schemas import PullRequestRef

log = get_logger("local_graph")

DEFAULT_BRANCHES = {"main", "master"}


# --- glue nodes + conditional edges -----------------------------------------


async def fix_select_node(state: GuardianState) -> dict:
    idx = state.get("findings_index", 0)
    finding = state["findings"][idx]
    return {
        "current_finding": finding,
        "fix_attempts": 0,
        "fix": None,
        "test_result": None,
        "last_test_output": None,
        "events": [f"fix_select: [{idx + 1}/{len(state['findings'])}] {finding.rule_id}"],
    }


async def fix_advance_node(state: GuardianState) -> dict:
    return {"findings_index": state.get("findings_index", 0) + 1}


def after_classify(state: GuardianState) -> str:
    return "fix_select" if state.get("findings") else "finalize"


def after_fix_generate(state: GuardianState) -> str:
    fix = state.get("fix")
    if fix is None:
        return "fix_advance"  # generation failed / budget out — skip this finding
    if fix.confidence == "low":
        return "fix_advance"  # never ship a low-confidence fix
    return "fix_apply"


def after_fix_apply(state: GuardianState) -> str:
    if (state.get("last_test_output") or "").startswith("Fix REJECTED"):
        from core.config import get_settings

        if state.get("fix_attempts", 0) < get_settings().max_fix_attempts:
            return "fix_generate"
        return "fix_advance"
    return "test_run"


def after_test_run(state: GuardianState) -> str:
    from core.config import get_settings

    result = state.get("test_result")
    if result and result.passed:
        return "pr_create"
    if state.get("fix_attempts", 0) < get_settings().max_fix_attempts:
        return "fix_generate"
    return "fix_advance"


def after_advance(state: GuardianState) -> str:
    if state.get("findings_index", 0) < len(state.get("findings", [])):
        return "fix_select"
    return "finalize"


async def _git(*args: str, cwd: str) -> tuple[int, str, str]:
    proc = await asyncio.create_subprocess_exec(
        "git",
        *args,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    return proc.returncode, out.decode().strip(), err.decode().strip()


async def local_router_node(state: GuardianState) -> dict:
    """Validate the repo and capture branch state. No cloning."""
    repo = state["repo_path"]
    rc, branch, err = await _git("rev-parse", "--abbrev-ref", "HEAD", cwd=repo)
    if rc != 0:
        raise RuntimeError(f"not a git repository: {repo} ({err[:200]})")
    return {
        "branch": branch,
        "workdir": repo,  # scanner/fix/test nodes operate on this key
        "events": [f"router: local repo {repo} on {branch}"],
    }


def fix_branch_name(finding, state: GuardianState) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", finding.rule_id.lower()).strip("-")[:40]
    return f"gitguardian/fix-{slug}-{state['scan_id'][:7]}"


def pr_body(state: GuardianState) -> str:
    f = state["current_finding"]
    fix = state["fix"]
    test = state["test_result"]
    return f"""## 🛡️ GitGuardian AI — Automated Security Fix

| | |
|---|---|
| **Rule** | `{f.rule_id}` |
| **Severity** | {f.severity.upper()} |
| **File** | `{f.file_path}:{f.start_line}` |
| **Scanner** | {f.tool} |
| **Confidence** | {fix.confidence} |
| **Cost** | ${state.get("llm_cost_usd", 0):.4f} |

### What was wrong
{f.message}

### The fix
{fix.explanation}

### Verification
- ✅ Re-scanned — original rule no longer fires
- ✅ Generated pytest suite **passed** in an isolated container ({test.duration_seconds:.1f}s)

> ⚠️ Generated by an AI agent on your machine — review before merging.
"""


async def local_pr_node(state: GuardianState) -> dict:
    """Commit the applied fix on a fix branch, push, open PR via gh.

    Auth is the user's own: git remote credentials for push, `gh` for the PR.
    Failure to push/PR is non-fatal — the commit stays local.
    """
    repo = state["repo_path"]
    finding = state["current_finding"]
    fix = state["fix"]
    branch = fix_branch_name(finding, state)
    files = [finding.file_path, fix.test_file_path]

    rc, _, err = await _git("checkout", "-b", branch, cwd=repo)
    if rc != 0:
        raise RuntimeError(f"cannot create fix branch: {err[:200]}")
    await _git("add", *files, cwd=repo)
    rc, _, err = await _git(
        "commit",
        "-m",
        f"fix(security): {finding.rule_id} in {finding.file_path}\n\n"
        "Generated by GitGuardian AI — review before merging.",
        cwd=repo,
    )
    if rc != 0:
        raise RuntimeError(f"cannot commit fix: {err[:200]}")

    pr_ref = PullRequestRef(number=0, url="", branch=branch)

    rc, _, err = await _git("push", "-u", "origin", branch, cwd=repo)
    if rc != 0:
        await log.awarning("push failed — fix committed locally only", error=err[:300])
        # go back to the user's branch with the commit kept on the fix branch
        await _git("checkout", state["branch"], cwd=repo)
        return {"prs": [pr_ref], "events": [f"pr: committed on {branch} (push failed)"]}

    if shutil.which("gh"):
        import tempfile
        from pathlib import Path

        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
            f.write(pr_body(state))
            body_path = f.name
        proc = await asyncio.create_subprocess_exec(
            "gh",
            "pr",
            "create",
            "--title",
            f"🛡️ Fix {finding.severity}: {finding.rule_id} in {finding.file_path}",
            "--body-file",
            body_path,
            "--head",
            branch,
            cwd=repo,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        out, gh_err = await proc.communicate()
        await asyncio.to_thread(os.unlink, body_path)
        if proc.returncode == 0:
            pr_ref = PullRequestRef(number=0, url=out.decode().strip(), branch=branch)
        else:
            await log.awarning("gh pr create failed", error=gh_err.decode()[:300])
    else:
        await log.awarning("gh CLI not found — branch pushed, open the PR from the link")

    # Return the working tree to the user's branch; the fix lives on the fix branch
    await _git("checkout", state["branch"], cwd=repo)

    # Persist for the dashboard (best-effort)
    try:
        import uuid as _uuid

        from sqlalchemy import select

        from core.db.models import FindingRow, FixRow, PullRequestRow
        from core.db.session import get_session_factory

        async with get_session_factory()() as session:
            finding_row = await session.scalar(
                select(FindingRow).where(
                    FindingRow.scan_id == _uuid.UUID(state["scan_id"]),
                    FindingRow.fingerprint == finding.fingerprint,
                )
            )
            if finding_row:
                original = ""
                try:
                    from pathlib import Path

                    original = (Path(repo) / finding.file_path).read_text(errors="replace")
                except OSError:
                    pass
                fix_row = FixRow(
                    id=_uuid.uuid4(),
                    finding_id=finding_row.id,
                    status="tests_passed",
                    model="local-agent",
                    attempts=state.get("fix_attempts", 0) + 1,
                    original_content=original[:65000],
                    fixed_content=fix.fixed_file_content[:65000],
                    test_content=fix.test_file_content[:65000],
                    explanation=fix.explanation,
                    tokens_in=state.get("llm_input_tokens", 0),
                    tokens_out=state.get("llm_output_tokens", 0),
                    cost_usd=state.get("llm_cost_usd", 0.0),
                )
                session.add(fix_row)
                await session.flush()
                session.add(
                    PullRequestRow(
                        id=_uuid.uuid4(),
                        fix_id=fix_row.id,
                        repo_path=repo,
                        number=pr_ref.number or None,
                        url=pr_ref.url,
                        branch=branch,
                    )
                )
                await session.commit()
    except Exception as e:
        await log.awarning("fix persistence failed (swallowed)", error=str(e)[:200])

    await log.ainfo("fix branch created", branch=branch, pr=pr_ref.url or "(local)")
    return {
        "prs": [pr_ref],
        "fixed_files": files,
        "events": [f"pr: {branch} {pr_ref.url or '(committed locally)'}"],
    }


async def local_finalize_node(state: GuardianState) -> dict:
    """Persist scan outcome; print the terminal summary."""
    from datetime import UTC, datetime

    from sqlalchemy import select

    from core.db.models import Scan
    from core.db.session import get_session_factory

    prs = state.get("prs", [])
    findings = state.get("findings", [])
    status = "no_findings" if not findings else ("awaiting_review" if prs else "completed")
    try:
        async with get_session_factory()() as session:
            scan = await session.scalar(select(Scan).where(Scan.id == state["scan_id"]))
            if scan:
                scan.status = status
                scan.llm_cost_usd = state.get("llm_cost_usd", 0.0)
                scan.trace_url = state.get("trace_url")
                scan.finished_at = datetime.now(UTC)
                if state.get("error"):
                    scan.error = state["error"]
            await session.commit()
    except Exception as e:
        await log.aerror("finalize failed (swallowed)", error=str(e)[:300])
    return {"events": [f"finalize: {status}"]}


def build_local_graph(checkpointer=None):
    g = StateGraph(GuardianState)

    g.add_node("router", local_router_node)
    g.add_node("scanner", scanner_node)
    g.add_node("classifier", classifier_node)
    g.add_node("fix_select", fix_select_node)
    g.add_node("fix_generate", fix_generator_node)
    g.add_node("fix_apply", _fix_apply_wrapper)
    g.add_node("test_run", test_generator_node)
    g.add_node("pr_create", local_pr_node)
    g.add_node("fix_advance", fix_advance_node)
    g.add_node("finalize", local_finalize_node)

    g.set_entry_point("router")
    g.add_edge("router", "scanner")
    g.add_edge("scanner", "classifier")
    g.add_conditional_edges("classifier", after_classify)
    g.add_edge("fix_select", "fix_generate")
    g.add_conditional_edges("fix_generate", after_fix_generate)
    g.add_conditional_edges("fix_apply", after_fix_apply)
    g.add_conditional_edges("test_run", after_test_run)
    g.add_edge("pr_create", "fix_advance")
    g.add_conditional_edges("fix_advance", after_advance)
    g.add_edge("finalize", END)

    return g.compile(checkpointer=checkpointer)


async def _fix_apply_wrapper(state: GuardianState) -> dict:
    """Apply + validate; validation failures become retry context."""
    try:
        await apply_fix(state["workdir"], state["current_finding"], state["fix"])
        await validate_with_rescan(state["workdir"], state["current_finding"])
    except FixValidationError as e:
        attempts = state.get("fix_attempts", 0) + 1
        await log.awarning("fix validation failed", error=str(e), attempts=attempts)
        return {
            "fix_attempts": attempts,
            "last_test_output": f"Fix REJECTED by validator: {e}",
            "events": [f"fix_apply: validation failed ({e})"],
        }
    return {"events": ["fix_apply: applied + re-scan clean"]}
