"use client";

import { useEffect, useState } from "react";
import { api } from "../../lib/api";

const AGENTS = {
  claude_code: {
    label: "Claude Code",
    hint: "Uses your Claude subscription via the installed CLI. Log in once with `claude` in your terminal — we detect the rest.",
  },
  codex: {
    label: "Codex CLI",
    hint: "Uses your OpenAI/ChatGPT account via the installed CLI. Log in once with `codex login` — we detect the rest.",
  },
};

export default function SettingsPage() {
  const [detect, setDetect] = useState(null);
  const [connection, setConnection] = useState(null);
  const [testing, setTesting] = useState(null);
  const [testResult, setTestResult] = useState({});
  const [config, setConfig] = useState({});
  const [langfuse, setLangfuse] = useState({ host: "http://localhost:3100", public_key: "", secret_key: "" });
  const [slackUrl, setSlackUrl] = useState("");
  const [flash, setFlash] = useState(null);
  const [error, setError] = useState(null);

  const loadConnection = () => api("/api/agents/connection").then(setConnection).catch(() => {});
  const loadDetect = () => api("/api/agents/detect").then(setDetect).catch(() => {});
  const loadConfig = () => api("/api/config").then(setConfig).catch(() => {});

  useEffect(() => {
    loadConnection();
    loadDetect();
    loadConfig();
  }, []);

  const connectAgent = async (provider) => {
    setFlash(null);
    setError(null);
    try {
      const r = await api("/api/agents/connect", {
        method: "POST",
        body: JSON.stringify({ provider }),
      });
      setFlash(`${AGENTS[provider].label} connected (${r.mode}) — no keys to paste.`);
      loadConnection();
    } catch (e) {
      setError(e.message);
    }
  };

  const testAgent = async (provider) => {
    setTesting(provider);
    setError(null);
    try {
      const r = await api("/api/agents/test-connection", {
        method: "POST",
        body: JSON.stringify({ provider }),
      });
      setTestResult((prev) => ({ ...prev, [provider]: r }));
    } catch (e) {
      setTestResult((prev) => ({ ...prev, [provider]: { ok: false, error: e.message } }));
    }
    setTesting(null);
  };

  const saveConfig = async (key, value, message) => {
    setFlash(null);
    setError(null);
    try {
      await api("/api/config", { method: "POST", body: JSON.stringify({ key, value }) });
      setFlash(message);
      loadConfig();
    } catch (e) {
      setError(e.message);
    }
  };

  return (
    <>
      <h1>Settings</h1>
      {flash && <div className="flash">{flash}</div>}
      {error && <div className="flash error">{error}</div>}

      <div className="panel">
        <h2>Your coding agent</h2>
        <p className="muted" style={{ marginBottom: 14 }}>
          Fixes are generated by your installed agent, billed to your own subscription.
          We auto-detect local CLIs — nothing to paste.
        </p>
        {connection?.connected && (
          <p style={{ marginBottom: 12 }}>
            Connected: <strong>{AGENTS[connection.provider]?.label ?? connection.provider}</strong>{" "}
            <span className="mono muted">({connection.fingerprint})</span>{" "}
            <button
              className="danger"
              onClick={() => api("/api/agents/connect", { method: "DELETE" }).then(loadConnection)}
            >
              Disconnect
            </button>
          </p>
        )}

        {Object.entries(AGENTS).map(([provider, a]) => {
          const d = detect?.[provider];
          const t = testResult[provider];
          return (
            <div className="panel" key={provider} style={{ background: "var(--bg)" }}>
              <div className="row">
                <strong>{a.label}</strong>
                <span className={`badge ${d?.connectable ? "success" : "failed"}`}>
                  {d ? (d.connectable ? "detected" : "not found") : "…"}
                </span>
              </div>
              <p className="muted" style={{ margin: "8px 0" }}>{a.hint}</p>
              <div className="row">
                <button
                  className="secondary"
                  disabled={!d?.connectable || testing === provider}
                  onClick={() => testAgent(provider)}
                >
                  {testing === provider ? "Testing…" : "Test connection"}
                </button>
                <button disabled={!d?.connectable} onClick={() => connectAgent(provider)}>
                  Connect
                </button>
              </div>
              {t && (
                <p style={{ marginTop: 8 }} className={t.ok ? "" : "flash error"}>
                  {t.ok ? `✓ Working — responded in ${t.latency_seconds}s` : `✗ ${t.error}`}
                </p>
              )}
            </div>
          );
        })}
      </div>

      <div className="panel">
        <h2>Observability (Langfuse)</h2>
        <p className="muted" style={{ marginBottom: 10 }}>
          Self-hosted Langfuse traces every scan — model calls, tokens, costs. Start it with{" "}
          <code>docker compose --profile langfuse up -d</code> then create keys at{" "}
          <a href="http://localhost:3100" target="_blank" rel="noreferrer">localhost:3100</a>.
          Status: {config.langfuse_secret_key ? "✅ configured" : "❌ not configured"}
        </p>
        <label>Host</label>
        <input type="text" value={langfuse.host} onChange={(e) => setLangfuse((l) => ({ ...l, host: e.target.value }))} />
        <label>Public key</label>
        <input type="text" value={langfuse.public_key} onChange={(e) => setLangfuse((l) => ({ ...l, public_key: e.target.value }))} placeholder="pk-lf-..." />
        <label>Secret key</label>
        <input type="password" value={langfuse.secret_key} onChange={(e) => setLangfuse((l) => ({ ...l, secret_key: e.target.value }))} placeholder="sk-lf-..." />
        <button
          onClick={async () => {
            await saveConfig("langfuse_host", langfuse.host, "Langfuse host saved");
            await saveConfig("langfuse_public_key", langfuse.public_key, "Langfuse keys saved");
            await saveConfig("langfuse_secret_key", langfuse.secret_key, "Langfuse configured — traces will appear on the next scan");
          }}
          disabled={!langfuse.public_key || !langfuse.secret_key}
        >
          Save Langfuse config
        </button>
      </div>

      <div className="panel">
        <h2>Slack notifications</h2>
        <label>Incoming webhook URL {config.slack_webhook_url && "(✅ set)"}</label>
        <input
          type="text"
          value={slackUrl}
          onChange={(e) => setSlackUrl(e.target.value)}
          placeholder="https://hooks.slack.com/services/..."
        />
        <button
          onClick={() => saveConfig("slack_webhook_url", slackUrl, "Slack webhook stored")}
          disabled={!slackUrl}
        >
          Save webhook
        </button>
      </div>
    </>
  );
}
